# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('midia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BluRay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.PositiveIntegerField()),
                ('unidades', models.PositiveIntegerField(default=0, verbose_name='Quantidade de unidades')),
                ('em_estoque', models.PositiveIntegerField(default=0, verbose_name='Em estoque')),
                ('duplo', models.BooleanField(default=False)),
                ('dual_layer', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.PositiveIntegerField()),
                ('unidades', models.PositiveIntegerField(default=0, verbose_name='Quantidade de unidades')),
                ('em_estoque', models.PositiveIntegerField(default=0, verbose_name='Em estoque')),
                ('duplo', models.BooleanField(default=False)),
                ('dual_layer', models.BooleanField(default=False)),
                ('regiao', models.PositiveIntegerField(default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNPJ')),
            ],
        ),
        migrations.AddField(
            model_name='dvd',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Fabricante'),
        ),
        migrations.AddField(
            model_name='dvd',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midia.Filme'),
        ),
        migrations.AddField(
            model_name='bluray',
            name='fabricante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.Fabricante'),
        ),
        migrations.AddField(
            model_name='bluray',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='midia.Filme'),
        ),
    ]
