# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluray',
            name='lote',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dvd',
            name='lote',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
