# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-24 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('end_tipo_logradouro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Logradouro')),
                ('end_logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('end_bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro')),
                ('end_numero', models.CharField(blank=True, default='S/N', max_length=5, null=True, verbose_name='Número')),
                ('end_complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('end_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência')),
                ('end_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('end_estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('vip', models.BooleanField(default=0, verbose_name='VIP?')),
                ('pontos_fidelidade', models.PositiveIntegerField(default=0, verbose_name='Pontos de Fidelidade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('end_tipo_logradouro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Logradouro')),
                ('end_logradouro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Logradouro')),
                ('end_bairro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro')),
                ('end_numero', models.CharField(blank=True, default='S/N', max_length=5, null=True, verbose_name='Número')),
                ('end_complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('end_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referência')),
                ('end_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('end_estado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='dependentes',
            field=models.ManyToManyField(to='locadora.Dependente', verbose_name='Dependetes'),
        ),
    ]
