# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('numero_de_oscar', models.IntegerField(default=0, verbose_name='Quantidade de Oscar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='diretor',
            options={'verbose_name': 'Diretor', 'verbose_name_plural': 'Diretores'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
