# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependente',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='cliente',
            name='dependentes',
            field=models.ManyToManyField(to='locadora.Dependente', verbose_name='Dependetes'),
        ),
    ]
