# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0002_auto_20160812_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('ano_producao', models.DateField(verbose_name='Data de Produção')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ator',
            options={'verbose_name': 'Ator', 'verbose_name_plural': 'Atores'},
        ),
        migrations.AddField(
            model_name='filme',
            name='atores',
            field=models.ManyToManyField(to='locadora.Ator', verbose_name='Atores'),
        ),
        migrations.AddField(
            model_name='filme',
            name='categorias',
            field=models.ManyToManyField(to='locadora.Categoria', verbose_name='Categorias'),
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locadora.Diretor', verbose_name='Diretor'),
        ),
    ]
