# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 11:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0005_auto_20160812_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='ano_producao',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2016)], verbose_name='Data de Produção'),
        ),
    ]
