# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 11:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0007_diretor_numero_de_oscar'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='numero_de_oscar',
            field=models.IntegerField(default=0, verbose_name='Quantidade de Oscar'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='ano_producao',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2016)], verbose_name='Ano de Produção'),
        ),
    ]
