# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0009_auto_20160812_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ator',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='diretor',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail'),
        ),
    ]
